### PR TITLE
Correct black formatting

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
`mypy` isn't happy either

**Comment by gliptak** [comment]
@csingley build is green

I rolled back 3.10/3.11 as nosetest/nose2 weren't running

please let me know if you are open to a PR moving to pytest

**Comment by csingley** [comment]
Thanks for cleaning up.  mypy keeps getting progressively more thorough.

Why do you want to migrate to pytest?  I mean I’m not opposed, but it’s a lot of thankless toil.  It would be nice to ditch nose.

**Comment by gliptak** [comment]
you can see at https://github.com/csingley/ofxtools/actions?query=branch%3Ablack1 the various fails for nosetest and nose2

let me see on pytest

**Pull request merged**
