### PR TITLE
add datetime types for -s -e -d

### PR DESCRIPTION
**Pull request by jettero**
These arguments don't actually work as is … this change should be the right fix.

### CODE REVIEW

**Comment by csingley** [comment]
They don't work for you?  Hmmm.  I use these options all the time.

Can you post an example with the errors thrown?  Python 2 or Python 3?

The way it's supposed to go is that these args get passed as strings to the models.bank.INCTRAN constructor, which sticks them into instances of Types.DateTime, which does the type conversion.

It's a bit spaghetti-ish, but Client just reuses the type conversion/validation system of Parser.

**Comment by jettero** [comment]
```
Traceback (most recent call last):
  File "/usr/local/python/python2.7/bin/ofxget", line 11, in <module>
    load_entry_point('ofxtools==0.5', 'console_scripts', 'ofxget')()
  File "/usr/local/python/python2.7/lib/python2.7/site-packages/ofxtools/Client.py", line 428, in main
    do_stmt(args)
  File "/usr/local/python/python2.7/lib/python2.7/site-packages/ofxtools/Client.py", line 255, in do_stmt
    dt = {d[2:]: D(getattr(args, d)) for d in ('dtstart', 'dtend', 'dtasof')}
  File "/usr/local/python/python2.7/lib/python2.7/site-packages/ofxtools/Client.py", line 255, in <dictcomp>
    dt = {d[2:]: D(getattr(args, d)) for d in ('dtstart', 'dtend', 'dtasof')}
  File "/usr/local/python/python2.7/lib/python2.7/site-packages/ofxtools/Types.py", line 241, in convert
    (value, type(value)))
ValueError: '20171105' is type '<type 'str'>'; can't convert to datetime
```

**Comment by csingley** [comment]
Yeah the actual bug was in line 15 of Types.py; I didn't test that under python 2.
Pushed a fix to master.  Thanks for reporting, my bad.

**Comment by jettero** [comment]
I'm happy as long as it's fixed. Thanks for the time either way. Closing PR.

**Pull request closed without merging**
