### PR TITLE
Enhancement/automated tests

### PR DESCRIPTION
**Pull request by turicas**
Hello, Christopher,

This pull request move old tests to an automated version, using `unittest` to describe them and `nosetests` to run (with test coverage support). Note that these tests are superficial since they don't assert many things -- they still need to be improved and automating the test running process is the first step, in my opinion. It also fixes a little bug in parsing "investment" OFX type (`yield` not being converted to `yld`).

Note: due to the number of leading spaces on many files, I suggest you to configure your `vim` with:

```vim
" Show trailing characters and undesirable spaces
set list
set listchars=tab:▸\ ,trail:·,nbsp:~

" Remove trailing spaces when save buffer
autocmd BufWritePre * :%s/\s\+$//e
```

### CODE REVIEW

**Comment by csingley** [comment]
I appreciate the help cleaning up.  I'm a finance guy not a programmer...  most of these seem like clear improvements.  Just a couple points of discussion.

Good catch on 'yield'; I missed that.  But the fix doesn't belong in Parser.py, which is really just a minimal extension of ElementTree to convert SGML to a tree structure in memory.  The heavy lifting of translating these data into a more Pythonic object/attribute model is actually done in models.py... probably _flatten() should really be a method of models.Aggregate, not Parser.Element, but in any case I'd rather see _flatten() kept as stripped down as possible, and put all the OFX-specific hacks & workarounds in one place inside models.py.  For an example of how to work around mismatches between OFX and Python, see the way models.MFINFO.__init__() extends models.Aggregate.__init__().  I suggest a similar approach for renaming 'yield' in MFINFO.__init__() and STOCKINFO.__init__()... find YIELD along with MFASSETCLASS and FIMFASSETCLASS, and if it's found, stick its value in extra_attrs['yld'] then remove the YIELD aggregate from the tree.  Similar treatment for STOCKINFO.__init__().  That way only those two aggregate types have to run that code.  If what I'm suggesting isn't obvious, I'll be happy to commit this change myself & you can base your pull request off that.

As for testing... I acknowledge its importance and my woeful inadequacy in this area.  Unit tests are an excellent idea and should be put in; your approach is a good one.  However, I'm not entirely convinced it's a good idea to remove facilities for running through large volumes of real-world OFX data from various FIs to see where they blow up; there is a lot of appallingly bad OFX data out there which blatantly violates not only the written spec but even the DTD.  Choking huge quantities of actual field data through the parser has been very helpful in judging where this slop can be gracefully accommodated vs. where it's just not worth the brain damage.

Thanks!

**Comment by turicas** [comment]
@csingley, thanks for your response. :)

- I'd like you to commit these changes about `yield` since I'm not well familiar with `ofxtools` source code. Could you please add a commit on top of my branch?
- Sorry for deleting your facilities for testing with real data -- I thought it were just something like "not automated unit tests" and then turned them into automated ones. I can work here to create a `scripts` directory with everything we had before at `ofxtools/tests` - what do you think? I think it's a better name IMHO. ;)

**Comment by csingley** [comment]
Sounds good.

**Comment by turicas** [comment]
@csingley, I just updated my branch with proposed changes and a little change in version. Your turn. ;-)

**Comment by csingley** [comment]
Regret that strict adherence to our QC policy of "no commits after the 2nd cocktail" necessitates occasional delay.

Thanks again.

**Comment by turicas** [comment]
Hahaha thank you! ;)

**Pull request merged**
