### PR TITLE
Issue 22: Some banks (Chase in this case) require a clientuid

### PR DESCRIPTION
**Pull request by PierreRochard**
Addresses https://github.com/csingley/ofxtools/issues/22 with an optional named argument

### CODE REVIEW

**Comment by csingley** [comment]
Hey Pierre, thanks for pushing these, that's great.  Couple things:

1. Sorry, what was the parse bug?  Was the source context manager not working for you?  Worked in my tests.  It's pretty trivial & we don't really need it here, but if we drop it we should probably make sure to explicitly close() the source.

2. I don't think we should hard-code an SQL schema in models.py.  Really the schema definition belongs in database.py, and it should be configurable by the user with None as the default.

From the [SQLAlchemy docs](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.Table): 

> schema –
> The schema name for this table, which is required if the table resides in a schema other than the default selected schema for the engine’s database connection. Defaults to None.
> If the owning MetaData of this Table specifies its own MetaData.schema parameter, then that schema name will be applied to this Table if the schema parameter here is set to None.

So what's needed is to set ofxalchemy.database.Base.metadata inside init_db.  Something like this:
```
def init_db(db_uri, schema=None, **kwargs):
    engine = create_engine(db_uri, **kwargs)
    Base.metadata.schema = schema
    Base.metadata.create_all(bind=engine)
    Session.configure(bind=engine)
    return engine
```
Then when you're setting up your application you'd call:
`engine = ofxalchemy.database.init_db(URI, 'ofx')`

Would you do me a favor and see if that works for you?  It's much cleaner.

**Comment by PierreRochard** [comment]
😬 sorry, I screwed up the branching, I meant to only pull request the first commit. Will fix this evening

**Comment by csingley** [comment]
np.  I checked in a modified ofxalchemy.database.init_db() for you.

**Comment by PierreRochard** [comment]
> np. I checked in a modified ofxalchemy.database.init_db() for you.

I fought with it some and then decided to just add "ofx" to my PostgreSQL search path since the table names are... unique to OFX. I'll eventually come back to this but I'm a happy camper for now.

Thanks,

Pierre

**Comment by csingley** [comment]
Well if you're happy I'm happy.

BTW just pushed a bunch of commits refactoring OFXClient to much nicer code... yes it handles CLIENTUID among other things.  You'll need to change your calls to OFXClient to reflect the new interface. Hopefully it's obvious from the code, but I intend to document everything better in the README.

**Pull request closed without merging**
